name: showcase_flutter_state_management
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^8.0.1

  provider: ^6.0.3

  flutter_riverpod: ^1.0.4
  riverpod: ^1.0.3

  flutter_redux: ^0.10.0
  redux: ^5.0.0

  flutter_mobx: ^2.0.6+1
  mobx: ^2.0.7+5

  http: ^0.13.5
  equatable: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.2.0
  mobx_codegen: ^2.0.7

flutter:
  uses-material-design: true